name:                tesladb
version:             0.2.0.0
github:              "dustin/tesladb"
license:             BSD3
author:              "Dustin Sallings"
maintainer:          "dustin@spy.net"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dustin/tesladb#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- wreq
- aeson
- lens-aeson
- bytestring
- generic-deriving
- text
- http-client
- containers
- sqlite-simple
- optparse-applicative
- network-uri
- async
- stm
- net-mqtt >= 0.8
- time
- mtl
- transformers
- unliftio
- unliftio-core
- vector
- exceptions
- monad-logger
- tesla

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  tesladb:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -eventlog
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - tesladb

  teslauth:
    main:                Main.hs
    source-dirs:         app/auth
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - tesladb

  teslacatcher:
    main:                Main.hs
    source-dirs:         app/catcher
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - tesladb
    - net-mqtt-rpc >= 0.2

  tesladbfix:
    main:                Main.hs
    source-dirs:         app/tsfix
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - tesladb
