name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Stack
      uses: haskell/actions/setup@v2
      with:
        stack-version: 'latest'

    - name: Cache Key
      id: cache_key
      run: echo ::set-output name=key::$(md5sum stack.yaml | awk '{print $1}')

    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ steps.cache_key.outputs.key }}

    - name: Build Snapshot
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        stack --resolver ghc-9.6.4 --no-terminal test --bench --only-snapshot

    - name: Build & Test
      run: |
        stack --resolver ghc-9.6.4 --no-terminal test --bench --no-run-benchmarks
        stack install
        mkdir dist
        cp $HOME/.local/bin/{teslauth,tesladb,teslacatcher} dist

    - name: Store Artifact
      uses: actions/upload-artifact@v3
      with:
        name: tesladb-${{ matrix.os }}
        path: dist
