name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.6.4'
        cabal-version: 'latest'

    - name: Update Cabal Package List
      run: cabal update

    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal', 'cabal.project*') }}

    - name: Build Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: cabal build --only-dependencies

    - name: Build & Test
      run: |
        cabal build all
        cabal test all
        cabal install exe:teslauth exe:tesladb exe:teslacatcher --installdir=./dist --overwrite-policy=always

    - name: Store Artifact
      uses: actions/upload-artifact@v3
      with:
        name: tesladb-${{ matrix.os }}
        path: dist